/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DesafioJava;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse.BodyHandlers;
import java.util.ArrayList;
import java.util.Set;

import com.google.common.reflect.TypeToken;
import com.google.gson.GsonBuilder;

import DesafioJava.Domain.Account;
import DesafioJava.Questions.*;

public class App {
    public static void main(String[] args) {
	
	System.out.println("Desafio de Fundamentos Mobile...");
	
	var client = HttpClient.newHttpClient();
        var request = HttpRequest.newBuilder()
	          .uri(URI.create("https://igti-film.herokuapp.com/api/accounts"))
	          .build();
	
	try {
	    System.out.println("Starting request...");
	    var response = client.send(request, BodyHandlers.ofString());
	    
	    System.out.println("Serializing JSON");
	    var jsonParser = new GsonBuilder().create();
	    
	    ArrayList<Account> accounts = jsonParser.fromJson(response.body(), new TypeToken<ArrayList<Account>>() {}.getType());
	    
	    System.out.println("Answering....");
	    
	    var questions = Set.of(
		new CalcTotalOfHighestAccPerAgency(),
		new GetClientWHighestBalanceAtAg10(),
	        new GetClientWLowestBalanceAtAg47(),
	        new GetNextId(),
	        new HigherThan100OnAgency33(),
	        new HighestBalanceAgency(),
	        new HowManyAccAtAg47(),
	        new HowManyAccWNameMariaAtAg47(),
	        new LowestBalanceAgency(),
	        new SumOfDeposits(),
	        new Top3LowestBalanceAtAg47(),
	        new TotalHigherThan100()
	    );
	    
	    for (var q : questions) {
		q.execute(accounts);
	    }
	    
	    
	} catch (IOException e) {
	    e.printStackTrace();
	} catch (InterruptedException e) {
	    e.printStackTrace();
	}

    }
}
